@echo off
echo Creating backup branch...
git checkout -b feature/cortex-integration-2026-02-01
echo Staging files...
git add .
echo Committing...
git commit -m "Saving stable Cortex setup: Gemini 2.0, run-with-env.mjs, and UI script fixes"
echo Backup Complete.
